before_cache:
- rm -rf $HOME/.m2/repository/org/antlr
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do
  du -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line
  $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
before_install:
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
- f="./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh"; ! [ -x "$f" ] || "$f"
before_script:
- find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do rm -rf $line; done;find
  $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
cache:
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Antlr4
  - $HOME/Library/Caches/Homebrew
  - $HOME/CACHE
  timeout: 600
language: java
matrix:
  include:
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=LEXER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=PARSER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=RECURSION
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=LEXER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: main-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=PARSER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: main-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=RECURSION
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: main-test
  - compiler: clang
    dist: xenial
    env:
    - TARGET=swift
    - GROUP=ALL
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=LEXER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=PARSER
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=RECURSION
    os: osx
    osx_image: xcode10.1
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - env: TARGET=java
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - env: TARGET=java
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: smoke-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=LEXER
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=PARSER
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=RECURSION
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: extended-test
  - dist: trusty
    env: TARGET=javascript
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: main-test
  - dist: trusty
    env: TARGET=go
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW | wc -l))
    stage: main-test
script:
- touch /tmp/NOW;echo SCRIPT_START $(date)
- 'cd runtime-testsuite;

  travis_wait 40 ../.travis/run-tests-$TARGET.sh;

  rc=$?;

  cat target/surefire-reports/*.dumpstream || true;

  exit $rc

  '
- echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
  -name TEST-*.xml -newer /tmp/NOW | wc -l))
stages:
- smoke-test
- main-test
- extended-test
sudo: true
